FROM node:alpine

# Set the working directory
WORKDIR /app

# Copy the package.json and package-lock.json files first
COPY /frontend/package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the frontend code
COPY /frontend/ ./

# Expose the port
EXPOSE 3000

# Run the development server
CMD npm run dev