services:
  postgres-db:
    build:
      context: .
      dockerfile: ./build/postgres/Dockerfile
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: prod_latest
    volumes:
      - pg_data:/var/lib/postgresql/data

  flask-app:
    volumes:
      - ./backend:/app
    build:
      context: .
      dockerfile: ./build/backend/Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - postgres-db
    environment:
      POSTGRES_PORT: 5432
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: prod_latest
      FLASK_DEBUG: 1

  vue-app:
    volumes:
      - /app/node_modules
      - ./frontend:/app
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    environment:
      - HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true

  nginx:
    volumes:
      - ./build/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    build:
      context: .
      dockerfile: ./build/nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - flask-app
      - vue-app

volumes:
  pg_data:
